### ISSUE TITLE
如果数据放在云存储或者CDN访问就会报错

### ISSUE THREAD

**Issue by Feyman88** [ciaoca/cxSelect#12]
Request header field X-API-REQUEST is not allowed by Access-Control-Allow-Headers in preflight response.
采取这种 JS 里面获取 json 数据 ，是很不合理的一种方式，可以通过在数据文件里面 执行 js 然后将数据继承到现有变量，在程序中直接调用就好了

**Comment by ciaoca** [comment]
这是一个常见的跨域问题，有各种解决办法，可自行 Google 了解。
另外，除了设置参数```url```，可以自己先使用其他方法获取到 JSON 数据，然后再调用 cxSelect 时使用参数```data```赋值即可。
