### ISSUE TITLE
在一个页面上有多个实例，怎么样让cityData.min.json只调用一次

### ISSUE THREAD

**Issue by linzy410** [ciaoca/cxSelect#13]
$.cxSelect.defaults.url = '/statics/cxSelect/js/cityData.min.json';
我在调用之前设置全局变量，没有效果

**Comment by ciaoca** [comment]
$.cxSelect.defaults.url 是一个变量，所以并不会认为始终是同一个数据来源。

如果希望减少请求数，那么可以自己通过 ajax 获取数据，然后赋值给 ```$.cxSelect.defaults.data```；
或者在 ajax 获取数据后，保存到一个全局变量，再通过 ```$('#element_id').cxSelect({data: yourCityData})```
