### ISSUE TITLE
github 下载的demo 直接运行index.html 报错

### ISSUE THREAD

**Issue by zuwensong** [ciaoca/cxSelect#15]
jquery.js:9664 XMLHttpRequest cannot load file:///C:/Users/weizong.gao/Desktop/%E6%96%B0%E5%BB%BA%E6%96%87%E4%BB%B6%E…E6%96%B0%E5%BB%BA%E6%96%87%E4%BB%B6%E5%A4%B9/cxSelect/js/cityData.min.json. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.

**Comment by ciaoca** [comment]
使用 ajax 获取 json 文件需要在服务器环境下，直接允许不能获取。
