### ISSUE TITLE
HTML5的data自定义属性大写问题

### ISSUE THREAD

**Issue by hymanomg** [ciaoca/cxSelect#38]
version 1.4.2 
`_queryName = self.selectArray[j].data('queryName');`
`data-queryName `浏览器会自动转为小写的`data-queryname`，从而导致`_queryName `为`undefined`

**Comment by ciaoca** [comment]
data 属性在 javascript 中使用驼峰命名方式
在 html 中使用横向命名方式，所以在 queryName 获取的是 data-query-name 的值
