### ISSUE TITLE
README.md 中示例代码错误

### ISSUE THREAD

**Issue by vem** [ciaoca/cxSelect#41]
$('#element_id').cxSelect({
  url: 'cityData.min.json'                // 提示：如果服务器不支持 .json 类型文件，请将文件改为 .js 文件
  selects: ['province', 'city', 'area'],  // selects 为数组形式，请注意顺序
  emptyStyle: 'none'
});

应为:
$('#element_id').cxSelect({
  url: 'cityData.min.json',               // 提示：如果服务器不支持 .json 类型文件，请将文件改为 .js 文件
  selects: ['province', 'city', 'area'],  // selects 为数组形式，请注意顺序
  emptyStyle: 'none'
});

第二行缺少 ,

**Comment by ciaoca** [comment]
谢谢指正
