### ISSUE TITLE
子级怎么设置默认值

### ISSUE THREAD

**Issue by Yansor** [ciaoca/cxSelect#42]
子级怎么设置默认值,  比如子级我先设置: 选择市  现在直接自己是空的

**Comment by ciaoca** [comment]
每一级的设置都一样
<option value="yourValue" selected>yourName</option>

**Comment by Yansor** [comment]
大概在: self.selectArray[i].empty().prop('disabled', true);
这个 .empty() 把 子级的 option 都清除掉了

**Comment by ciaoca** [comment]
你需要确保设置的默认值，在联动数据里存在，如果子级并不存在于指定的默认父级里，自然是没有的

**Comment by Yansor** [comment]
> 你需要确保设置的默认值，在联动数据里存在，如果子级并不存在于指定的默认父级里，自然是没有的

我这边的一个需求: 
省市区 三个select 都必须显示出来占位,   而且默认情况下, 下一级默认啥也没有的时候, 要显示下默认的文字: 选择市/区, 而不是没有的时候什么都不显示

感谢及时回复

**Comment by ciaoca** [comment]
看文档介绍
参数：`emptyStyle`, `required`, `firstTitle`

**Comment by Yansor** [comment]
在默认打开页面,  初始化的时候,  一级是可以按配置显示(并且有选择操作的时候, 子集会按配置的方式出现) 
但是子集在没有做出选择一级的时候,   二级/三级都是不显示option的,即使设置了 您说的这三个参数
