### ISSUE TITLE
jsonSpace不生效

### ISSUE THREAD

**Issue by yoyo0926** [ciaoca/cxSelect#47]
要按照demo里的直接返回，不包裹在data里面数据是正常的，只要包裹了，数据就出不来

`        $('#w1').cxSelect({
            url: API_URL + 'v1/site/region-tree',
            selects: ['province', 'city', 'district'],  // selects 为数组形式，请注意顺序
            emptyStyle: 'hidden',
            jsonSpace: 'data',
            jsonName: 'region_name',
            jsonValue: 'region_code',
            jsonSub: 'children'
        });
`

麻烦看一下jsonSpace的问题，我尝试切换到jquery.cxselect.js version 1.3.11时，发现jsonSpace是生效的，但是emptyStyle又不生效了

**Comment by ciaoca** [comment]
demo 示例已增加，可参考
http://ciaoca.github.io/cxSelect/demo/oneself.html

**Comment by yoyo0926** [comment]
谢谢，我把jquery.cxselect.js看了一遍，发现在218行

if ($.isArray(data)) {

这个判断条件有问题，因为我给了jsonSpace，我给它加了一个反向判断，改成 if (!$.isArray(data)) {

就生效了..

**Comment by yoyo0926** [comment]
<fieldset id="global_location">
<legend>全球常见国家城市联动</legend>
<section>
<select class="country" data-first-title="选择国家"></select>
<select class="state"></select>
<select class="city"></select>
<select class="region"></select>
</section>
</fieldset>

<script src="//[cdn.staticfile.org/zepto/1.0/zepto.min.js](http://cdn.staticfile.org/zepto/1.0/zepto.min.js)"></script>
<script src="http://ciaoca.github.io/cxSelect/js/jquery.cxselect.js"></script>
<script>
(function() {
var dataCustom = {
code:200,
message: '模拟数据',
data: [
{v: '1', n: '第一级 >', 's': [
{v: '2', n: '第二级 >', 's': [
{v: '3', n: '第三级 >', 's': [
{v: '4', n: '第四级 >', 's': [
{v: '5', n: '第五级 >', 's': [
{v: '6', n: '第六级 >'}
]}
]}
]}
]}
]},
{v: 'number', n: '测试数字', 's': [
{v: 'text number', n: '文本类型', 's': [
{v: '4', n: '4'},
{v: '5', n: '5'},
{v: '6', n: '6'},
{v: '7', n: '7'},
{v: '8', n: '8'},
{v: '9', n: '9'},
{v: '10', n: '10'}
]},
{v: 'int number', n: '数值类型', 's': [
{v: 11, n: 11},
{v: 12, n: 12},
{v: 13, n: 13},
{v: 14, n: 14},
{v: 15, n: 15},
{v: 16, n: 16},
{v: 17, n: 17}
]}
]},
{v: 'boolean',n: 'Boolean 类型', 's': [
{v: true ,n: true},
{v: false ,n: false}
]},
{v: 'other', n: '奇怪的值', s: [
{v: [], n: '数组（空）'},
{v: [1,2,3], n: '数组（数值）'},
{v: ['a','b','c'], n: '数组（文本）'},
{v: new Date(), n: '日期'},
{v: new RegExp('\\d+'), n: '正则对象'},
{v: /\d+/, n: '正则直接量'},
{v: {}, n: '对象'},
{v: document.getElementById('custom_data'), n: 'DOM'},
{v: null, n: 'Null'},
{n: '未设置 value'}
]},
{v: '' , n: '无子级'}
]
}


// 全球常见国家城市联动
$('#global_location').cxSelect({
data: dataCustom,
selects: ['country', 'state', 'city', 'region'],
emptyStyle: 'none', // 子集无数据时 select 元素的显示状态。可设置为："none"(display:none), "hidden"(visibility:hidden)
jsonSpace: 'data',
});

})();
</script>

这个是按照demo的json数据改了一下，加了一层data，作者可以跑一下试试

**Comment by yoyo0926** [comment]
`<fieldset id="global_location">
<legend>全球常见国家城市联动</legend>
<section>
<select class="country" data-first-title="选择国家"></select>
<select class="state"></select>
<select class="city"></select>
<select class="region"></select>
</section>
</fieldset>

<script src="//[cdn.staticfile.org/zepto/1.0/zepto.min.js](http://cdn.staticfile.org/zepto/1.0/zepto.min.js)"></script>
<script src="http://ciaoca.github.io/cxSelect/js/jquery.cxselect.js"></script>
<script>
(function() {
var dataCustom = {
code:200,
message: '模拟数据',
data: [
{v: '1', n: '第一级 >', 's': [
{v: '2', n: '第二级 >', 's': [
{v: '3', n: '第三级 >', 's': [
{v: '4', n: '第四级 >', 's': [
{v: '5', n: '第五级 >', 's': [
{v: '6', n: '第六级 >'}
]}
]}
]}
]}
]},
{v: 'number', n: '测试数字', 's': [
{v: 'text number', n: '文本类型', 's': [
{v: '4', n: '4'},
{v: '5', n: '5'},
{v: '6', n: '6'},
{v: '7', n: '7'},
{v: '8', n: '8'},
{v: '9', n: '9'},
{v: '10', n: '10'}
]},
{v: 'int number', n: '数值类型', 's': [
{v: 11, n: 11},
{v: 12, n: 12},
{v: 13, n: 13},
{v: 14, n: 14},
{v: 15, n: 15},
{v: 16, n: 16},
{v: 17, n: 17}
]}
]},
{v: 'boolean',n: 'Boolean 类型', 's': [
{v: true ,n: true},
{v: false ,n: false}
]},
{v: 'other', n: '奇怪的值', s: [
{v: [], n: '数组（空）'},
{v: [1,2,3], n: '数组（数值）'},
{v: ['a','b','c'], n: '数组（文本）'},
{v: new Date(), n: '日期'},
{v: new RegExp('\\d+'), n: '正则对象'},
{v: /\d+/, n: '正则直接量'},
{v: {}, n: '对象'},
{v: document.getElementById('custom_data'), n: 'DOM'},
{v: null, n: 'Null'},
{n: '未设置 value'}
]},
{v: '' , n: '无子级'}
]
}


// 全球常见国家城市联动
$('#global_location').cxSelect({
data: dataCustom,
selects: ['country', 'state', 'city', 'region'],
emptyStyle: 'none', // 子集无数据时 select 元素的显示状态。可设置为："none"(display:none), "hidden"(visibility:hidden)
jsonSpace: 'data',
});

})();
</script>`

**Comment by yoyo0926** [comment]
`

<fieldset id="global_location">
<legend>全球常见国家城市联动</legend>
<section>
<select class="country" data-first-title="选择国家"></select>
<select class="state"></select>
<select class="city"></select>
<select class="region"></select>
</section>
</fieldset>

`

**Comment by yoyo0926** [comment]
似乎这个代码不太好上传，我放在一个html文件里了。
[test3.html.zip](https://github.com/ciaoca/cxSelect/files/8281722/test3.html.zip)

**Comment by yoyo0926** [comment]
上面代码不太好弄，我将文件整理成一个html，引用的是示例站上的Js，可以直接下载运行的
[test3.html.zip](https://github.com/ciaoca/cxSelect/files/8281734/test3.html.zip)

这个是按照demo的json数据改了一下，加了一层data，作者可以跑一下试试，它确实不生效

**Comment by ciaoca** [comment]
`jsonSpace` 主要是为了解决使用接口获取数据，无需另外处理，方便使用。
如果是自定义的数据，直接赋值就行，没有必要使用该参数，例如:  `data: dataCustom.data`
以及自行通过 ajax 获取到数据处理后，再调用参考：
```
ajax(...).done((res) => {
  $('#city_china').cxSelect({
    data: res.data
    selects: ['province', 'city', 'area']
  });
});
```
