### ISSUE TITLE
required的控制对象

### ISSUE THREAD

**Issue by blazen** [ciaoca/cxSelect#6]
如省市区联动中，我常常遇到的一个需求就是，省是非必选的，但是如果选中了省，那么市与区都会自动选择第一个作为默认值，所以在子级联项中就不应该有<option value="firstValue">firstTitle</option>。
如果将其扩展成给每一个selects都配置自己的配置对象{name：？， required：？}就更好了。

**Comment by ciaoca** [comment]
考虑下，目前配置参数基本都能独立配置了，也许下一次更新会加上吧
