### ISSUE TITLE
有方法能把值写回到选择框去吗

### ISSUE THREAD

**Issue by zxnhl702** [ciaoca/cxSelect#7]
我这有一个页面　　每次打开时会从数据库中取这一条的省市区数据　　但是我没找到能把数据写到选择框中的方法

由于页面用ajax的方式取数据　所以需要在csSelect实例化之后才能写入数据　不知道有没有相关的方法

**Comment by ciaoca** [comment]
可以使用自定义数据，数据格式相同，参考：http://code.ciaoca.com/jquery/cxselect/demo/custom.html

**Comment by wyolaf** [comment]
同问，在数据库中取出数据来 然后在下拉栏中显示 但是省市区依然可以正常选择，只是在页面加载的时候把数据库中的值通过插件的下拉框现实出来，方便解释一下怎么用吗

**Comment by ciaoca** [comment]
@wyolaf 请看文档和 Demo
问题描述不是很明白，不同问题请开新 issues
