### ISSUE TITLE
此项目能否发布到npm上？

### ISSUE THREAD

**Issue by remxcode** [ciaoca/cxSelect#9]

**Comment by ciaoca** [comment]
v1.4.0 已发布到 npm，1.4.x 更新部分变更，详见：[1.4.0 更新说明](https://github.com/ciaoca/cxSelect/wiki/1.4.0-%E6%9B%B4%E6%96%B0%E8%AF%B4%E6%98%8E)

**Comment by ciaoca** [comment]
[npm cxselect](https://www.npmjs.com/package/cxselect)

**Comment by remxcode** [comment]
thanks
